### ISSUE TITLE
20201017 release on PyPi

### ISSUE THREAD

**Issue by fstephany** [MicrochipTech/cryptoauthlib#200]
It seems that the [latest version on PyPi](https://pypi.org/project/cryptoauthlib/#history) is the 20200912. 
Is there any issue to push the latest release on PyPi? Or is there another mechanism to retrieve the package?

**Comment by bryan-hunt** [comment]
There is an issue in the appveyor builds I’m trying to resolve so it is delayed until that is working again (otherwise the pypi release ends up with only some of wheels). From a CI perspective with the major shift in the way Travis-CI is as well I believe I’m going to be transitioning everything over to GitHub actions next week.

**Comment by bryan-hunt** [comment]
@fstephany This should now be fixed with the release of v3.2.5 (20201130)
