### ISSUE TITLE
Serial mismatch between old version and 3.3.3 release

### ISSUE THREAD

**Issue by pnaulls** [MicrochipTech/cryptoauthlib#279]
I'm chasing a problem with a mismatch between versions reporting the serial number with p11tool. The issue seems to be with the versions of cryptoauthlib.  

Using the version in the documentation on the Microchip site and the recommend branch (version from sometime in 2018):

(git clone --single-branch -b pkcs11 https://github.com/MicrochipTech/cryptoauthlib)

`# p11tool --list-all
Object 0:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE;object=device;type=private
Token '0123EE' with URL 'pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE' requires user PIN
Enter PIN: 
        Type: Private key (EC/ECDSA-SECP256R1)
        Label: device
        Flags: CKA_PRIVATE; CKA_SENSITIVE; 
        ID: 

Object 1:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE;object=device;type=public
        Type: Public key (EC/ECDSA-SECP256R1)
        Label: device
        ID: 
`
The examples suggest this is correct output, and the token should indeed bet 0123EE.  From the test suite:

`serial number:
01 23 BA 8B 87 9C 78 0F EE`

(This is run using the 3.3.3 library)

However with this library:

`p11tool --list-all 
Object 0:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE;object=device;type=private
Token '0123EE' with URL 'pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE' requires user PIN
Enter PIN: 
        Type: Private key (EC/ECDSA-SECP256R1)
        Label: device
        Flags: CKA_PRIVATE; CKA_SENSITIVE; 
        ID: 

Object 1:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=BA8B879C780F;token=0123EE;object=device;type=public
        Type: Public key (EC/ECDSA-SECP256R1)
        Label: device
        ID: `

I don't think this is correct. I did try to use 3.3.2, but it has some code issues with OpenSSL integration etc, and I didn't want to waste any more time on it.  

p11-kit is 0.24, openssl is 1.1.1l and gnutls is 3.7.2. 

Let me know what further information I can provide.

**Comment by bryan-hunt** [comment]
The reported problem has nothing to do with the token name. 

You are getting the prompt to login to the token because you have told the library to require it by setting the "user_pin_handle" option in your configuration file. 

As an FYI the token name is set here: https://github.com/MicrochipTech/cryptoauthlib/blob/main/app/pkcs11/slot.conf.tmpl#L6-L8

Also the pkcs11 branch is a legacy branch for people that still are pulling it in their yocto/buildroot configurations. Hopefully it goes away soon. Regardless the documentation no longer points to it.

**Comment by pnaulls** [comment]
Thanks for the clarification. Sorry, I added some confusion by pasting the wrong output for the 3.3.3 version. The serial number is reported differently:

# p11tool --list-all 
Object 0:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=23BA8B879C780FEE;token=00ABC;object=device;type=private
        Type: Private key (EC/ECDSA-SECP256R1)
        Label: device
        Flags: CKA_PRIVATE; CKA_SENSITIVE; 
        ID: 

Object 1:
        URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=23BA8B879C780FEE;token=00ABC;object=device;type=public
        Type: Public key (EC/ECDSA-SECP256R1)
        Label: device
        ID: 
``

Which is correct? 23BA8B879C780FEE or BA8B879C780F?

Incidentally, regarding documentation, The PKI application note:

https://www.microchip.com/en-us/application-notes/an8983 appear to be quite old (2016), and refers to commands such as "client-provision" in the test application. 

I also have some build fixes against OpenSSL/OpenWrt; I'll do a separate issue for those.

**Comment by bryan-hunt** [comment]
Our cryptoauth devices have 9 byte device identifiers. The pkcs11 serial number field is 16 characters wide [pkcs11 v2.40 token info](https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc323024051). The cryptoauth device identifier is composed of 6 bytes of basically a UUID, the other three bytes are programed fields that we assign to different part series, the whole value is obviously checked to be globally unique. If you dig into the read serial number function you'll see it is pulling these values from different areas in memory. 

The change was made to enable customers to set their own token labels in the slot configuration (my previous comment) so the token serial number field was maximized to store 8 bytes of the device id. The 9th byte (01) is unlikely to change in the foreseeable future. If it does then we will have to add an alternative representation of the field rather than hex that will become a pkcs11 configuration option (most likely base32hex over a 10 byte field left padded with 0 to avoid and invalid character).

If your existing software requires the token identifier to be 0123EE then you can simply add it to your configuration file `label = 0123EE`.  There is not any method to modify how the serial number is being displayed today and it will report 8 bytes of data rather than the 6 it was previously.

**Comment by pnaulls** [comment]
Ah, thanks. I'm not tied to any particular values, but that explains things - it's just important to have a base line of how things work and are reported. Hopefully you can get some of the documentation updated. Closing.
