### ISSUE TITLE
ATECC508A cryptography intigration with ESP32-IDF 

### ISSUE THREAD

**Issue by nagarathna321** [MicrochipTech/cryptoauthlib#28]
HI I am Working on ATECC508A cryptography with ESP32-IDF  please any one help me to create read and right functions with I2C lines

**Comment by bryan-hunt** [comment]
An ESP32 Hal driver has been added to the library now which you can see in:
https://github.com/MicrochipTech/cryptoauthlib/blob/master/lib/hal/hal_esp32_i2c.c
https://github.com/MicrochipTech/cryptoauthlib/blob/master/lib/hal/hal_esp32_timer.c

In order to use it does require a bit of set up that I've tried to detail below. If you're familiar with how esp-idf project build this should be fairly familiar:

Copy cryptoauthlib into your esp32 project and in the cryptoauthlib folder add a component.mk file:

```
CRYPTOAUTHLIB_DIR := lib

COMPONENT_SRCDIRS := $(CRYPTOAUTHLIB_DIR)/atcacert \
                     $(CRYPTOAUTHLIB_DIR)/basic \
                     $(CRYPTOAUTHLIB_DIR)/crypto \
                     $(CRYPTOAUTHLIB_DIR)/crypto/hashes \
                     $(CRYPTOAUTHLIB_DIR)/host \
                     $(CRYPTOAUTHLIB_DIR)/mbedtls \
                     $(CRYPTOAUTHLIB_DIR)

COMPONENT_ADD_INCLUDEDIRS := $(CRYPTOAUTHLIB_DIR)

CFLAGS+=-DESP32 -DATCA_HAL_I2C -DATCA_PRINTF
```

Create a seperate dummy folder named cryptoauthlib_hal and create another component.mk file:

```
CRYPTOAUTHLIB_DIR := ../cryptoauthlib/lib

COMPONENT_SRCDIRS := $(CRYPTOAUTHLIB_DIR)/hal

COMPONENT_OBJS := $(CRYPTOAUTHLIB_DIR)/hal/atca_hal.o $(CRYPTOAUTHLIB_DIR)/hal/hal_freertos.o $(CRYPTOAUTHLIB_DIR)/hal/hal_esp32_i2c.o $(CRYPTOAUTHLIB_DIR)/hal/hal_esp32_timer.o 

COMPONENT_ADD_INCLUDEDIRS := $(CRYPTOAUTHLIB_DIR)

CFLAGS+=-DESP32 -DATCA_HAL_I2C -DATCA_PRINTF -DATCA_USE_RTOS_TIMER

cryptoauthlib/lib/hal/hal_freertos.o: CFLAGS+= -I$(IDF_PATH)/components/freertos/include/freertos
```


In the root project directory add the following to your component.mk file (or create it if it does not exist)
```
EXTRA_COMPONENT_DIRS := cryptoauthlib cryptoauthlib_hal
```

Generally your file structure would look like the following when you're done setting it up:

```
<project root>
    cryptoauthlib/
        lib/
        component.mk
    cryptoauthlib_hal/
        component.mk
    app_main.c
    component.mk
```
