### ISSUE TITLE
Not able to write keys and certificate into ATECC608B chip

### ISSUE THREAD

**Issue by ashishpatel789** [MicrochipTech/cryptoauthlib#280]
I am using ATECC608B `ATECC608B-SSHDA-T` chip and cryptoauthlib version 3.2. device is wakeup successfully few of the function working correct but AES, key writing and certificate writing is always failing. also encryption decryption is not working.

My Chip have this configuration locked.
```
0x01 0x23 0x50 0x66 0x00 0x00 0x50 0x00 0x7c 0x63 0x85 0x50 0xee 0xc0 0x35 0x00
0xc0 0x00 0x00 0x83 0x20 0x85 0x20 0x8f 0x20 0xc4 0x8f 0x8f 0x8f 0x8f 0x8f 0x9f 
0x8f 0x0f 0x0f 0x8f 0x0f 0x8f 0x0f 0x8f 0x0f 0x8f 0x0f 0x8f 0x0f 0x00 0x00 0x00 
0x00 0xaf 0x8f 0xff 0xff 0xff 0xff 0x00 0x00 0x00 0x00 0xff 0xff 0xff 0xff 0x00 
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xff 0x00 0x00 0x00 0x00 0x00 0x00 0x33 
0x00 0x33 0x00 0x33 0x00 0x1c 0x00 0x1c 0x00 0x1c 0x00 0x1c 0x00 0x3c 0x00 0x1a 
0x00 0x3a 0x00 0x1a 0x00 0x3a 0x00 0x3a 0x00 0x3c 0x00 0x3c 0x00 0x1c 0x00 0x00
```
 
On writing public key on slot 15 and AES key on slot 9  i am getting error `ATCA_EXECUTION_ERROR` or 0xF4 error code.

**Comment by bryan-hunt** [comment]
Product support questions need to be submitted through the [mySupport portal](https://microchipsupport.force.com/s/) where Microchip's global team of FAEs can work on your use case and questions.

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)

The configuration of this part makes it mostly unusable, especially if you didn't program anything into it before locking the data zone - you also disabled AES which is why the AES command is failing.
