### ISSUE TITLE
Help configuring ATECC508 Slot Configuration

### ISSUE THREAD

**Issue by umanayana** [MicrochipTech/cryptoauthlib#32]
Hello, 

I am trying to figure out how to setup the slot configuration (SlotConfig Byte 20 to 51) for the following 

1. Generate a public key using (`genkey` command) from a private key stored in a slot? As far as I see Bit 0 and bit 1 needs to be set.

2. I want to perform ECDH operation on the chip using a given private key slot. But I do not want the master secret returned in unencrypted. The documentation says to set Bit 3 to 1. Which will store the master secret in `slot N|1`. What is `slot N|1`? How do I read from 'slot N|1`?

I also need to know how to run the `GenKey` command so that the private key is stored in the TempKey register? When I am performing ECDH I need to generate a new key pair using GenKey but I need to store the private key on the ATECC508. I want to use the TemKey register to do this. How can I achieve this?

**Comment by bryan-hunt** [comment]
Storing a private key in tempkey for use in ECDH is an ATECC608A feature only.

This is a product support question rather than a software/library bug. For product support you must talk to your assigned FAE or submit a request through the mySupport portal on [microchip.com](http://www.microchip.com/support/hottopics.aspx). [Instructions for using the mySupport portal](https://microchip.secure.force.com/microchipknowledge/articles/en_US/FAQ/How-to-submit-a-case)

**Comment by umanayana** [comment]
Thanks.
