### ISSUE TITLE
Tool to generate compressed certificates

### ISSUE THREAD

**Issue by govind-mukundan** [MicrochipTech/cryptoauthlib#77]
Is there any script or tool available to generate the compressed certificate given a standard certificate in DER or PEM?
Specifically, I would like to generate a compressed version of the Root certificate obtained from the provisioning kit - [AT88CKECCROOT](https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/AT88CKECCROOT)

**Comment by bryan-hunt** [comment]
I'm closing this issue due to it's age. 

The Trust Flex product line was created to make the process of developing a chain of trust much simpler. The [Trust Platform Design Suite](https://www.microchip.com/en-us/products/security-ics/trust-platform#Getting%20Started) is the preferred tool for exploring these parts and their use cases

https://www.microchip.com/en-us/products/security-ics/trust-platform#Getting%20Started
